# Generated by Django 4.1.7 on 2023-03-02 16:52

from django.db import migrations, models
import test_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.ImageField(upload_to=test_images.models.update_filename),
        ),
    ]
