"""add avatar for contact

Revision ID: 5b24d5f2744b
Revises: ee280df10699
Create Date: 2023-03-27 14:32:20.196365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b24d5f2744b'
down_revision = 'ee280df10699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'avatar')
    # ### end Alembic commands ###
