"""add role

Revision ID: 73699868892b
Revises: 71e24e697ba2
Create Date: 2023-03-25 21:07:45.316392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73699868892b'
down_revision = '71e24e697ba2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    op.drop_table('roles')
    # ### end Alembic commands ###
