# Generated by Django 4.1.7 on 2023-03-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
