# Generated by Django 4.1.7 on 2023-03-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_quotes', '0002_user_quote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
