# Generated by Django 4.1.7 on 2023-03-01 08:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_author_quote_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=500, size=None),
        ),
    ]
